listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;
srs_log_level       trace;

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

http_api {
    enabled         on;
    listen          1985;
}

rtc_server {
    enabled         on;
    listen          8000;
    candidate       $CANDIDATE;
}

vhost __defaultVhost__ {
    min_latency     on;

    tcp_nodelay     on;
    mr {
        enabled     off;
    }

    gop_cache       off;
    queue_length    10;
    time_jitter     off;
    mw_latency      0;

    play {
        gop_cache   off;
        queue_length 10;
    }

    publish {
        mr          off;
        firstpkt_timeout    5000;
        normal_timeout      5000;
    }

    hls {
        enabled     off;
    }

    dvr {
        enabled     off;
    }

    http_remux {
        enabled     off;
    }
}

